name = "Dyadics"
uuid = "7d70a868-7894-4498-a9f8-5da8f66d5551"
authors = ["Dyadics Contributors"]
version = "0.1.0"

[deps]

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
